/**
 * Job Controller — Full CRUD + helpers
 *
 * Handles all business logic for job postings:
 *  - List jobs (filtered, sorted, paginated + full-text search)
 *  - Get single job by slug or ID
 *  - Create, update, delete job
 *  - Publish / unpublish job
 *  - Increment view count
 *  - Get trending / featured jobs
 *  - Get related jobs
 */

const Job = require('../models/Job');
const slugify = require('slugify');

// ─── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Build a MongoDB sort query object from a sort key string.
 */
const buildSortQuery = (sort) => {
  switch (sort) {
    case 'oldest':    return { createdAt: 1 };
    case 'views':     return { viewCount: -1, createdAt: -1 };
    case 'trending':  return { isTrending: -1, viewCount: -1, createdAt: -1 };
    default:          return { createdAt: -1 }; // newest
  }
};

/**
 * Standard paginated response envelope
 */
const paginatedResponse = (res, { jobs, total, page, limit }) => {
  const totalPages = Math.ceil(total / limit);
  return res.json({
    success: true,
    data: jobs,
    pagination: {
      total,
      page,
      limit,
      totalPages,
      hasNextPage: page < totalPages,
      hasPrevPage: page > 1,
    },
  });
};

// ─── Controller Functions ──────────────────────────────────────────────────────

/**
 * GET /api/jobs
 * List jobs with filtering, sorting, pagination, and full-text search.
 */
exports.listJobs = async (req, res) => {
  let { page = 1, limit = 10, sort = 'newest', status = 'published', state, jobType, qualification, category, q, isTrending, isFeatured, age } = req.query;

  // Convert to numbers
  page = parseInt(page, 10) || 1;
  limit = parseInt(limit, 10) || 10;

  // Build filter
  const filter = { status };

  if (state)         filter.state = state;
  if (jobType)       filter.jobType = jobType;
  if (qualification) filter.qualification = qualification;
  if (category)      filter.category = category;
  if (isTrending !== undefined) filter.isTrending = isTrending === 'true';
  if (isFeatured !== undefined) filter.isFeatured = isFeatured === 'true';
  if (req.query.hasAdmitCard === 'true') filter.admitCardUrl = { $ne: '' };
  if (req.query.hasResult === 'true')    filter.resultUrl = { $ne: '' };

  // Age Filtering Logic
  if (age) {
    const ageNum = parseInt(age, 10);
    if (!isNaN(ageNum)) {
      filter.$and = filter.$and || [];
      filter.$and.push({
        $or: [
          { 'eligibility.minAge': { $lte: ageNum } },
          { 'eligibility.minAge': null },
          { 'eligibility.minAge': { $exists: false } },
        ],
      });
      filter.$and.push({
        $or: [
          { 'eligibility.maxAge': { $gte: ageNum } },
          { 'eligibility.maxAge': null },
          { 'eligibility.maxAge': { $exists: false } },
        ],
      });
    }
  }

  // Full-text search (uses the text index)
  if (q) filter.$text = { $search: q };

  const skip = (page - 1) * limit;
  const sortQuery = buildSortQuery(sort);

  // For text search, add relevance score projection and sort by score
  const projection = q ? { score: { $meta: 'textScore' } } : {};
  const textSort = q ? { score: { $meta: 'textScore' }, ...sortQuery } : sortQuery;

  const [jobs, total] = await Promise.all([
    Job.find(filter, projection)
      .sort(textSort)
      .skip(skip)
      .limit(limit)
      .select(
        'title slug organization state jobType qualification vacancy.total importantDates.applicationEnd ' +
        'featuredImage shortDescription viewCount isTrending isFeatured status publishedAt createdAt seo.metaDescription'
      )
      .lean(),
    Job.countDocuments(filter),
  ]);

  return paginatedResponse(res, { jobs, total, page, limit });
};

/**
 * GET /api/jobs/:identifier
 * Fetch a single job by slug (preferred) or MongoDB _id.
 * Also increments the view count asynchronously.
 */
exports.getJob = async (req, res) => {
  const { identifier } = req.params;

  // Determine if it looks like an ObjectId or a slug
  const isObjectId = /^[0-9a-fA-F]{24}$/.test(identifier);
  const query = isObjectId ? { _id: identifier } : { slug: identifier };

  const job = await Job.findOne(query)
    .populate('relatedJobs', 'title slug organization state jobType featuredImage shortDescription')
    .lean({ virtuals: true });

  if (!job) {
    return res.status(404).json({ success: false, message: 'Job not found' });
  }

  // Increment view count without blocking the response
  Job.incrementViews(job._id).catch(() => {}); // fire-and-forget

  return res.json({ success: true, data: job });
};

/**
 * POST /api/jobs
 * Create a new job posting. Slug auto-generated by the model pre-save hook.
 * Only accessible to authenticated admins.
 */
exports.createJob = async (req, res) => {
  // Attach the creating admin's ID
  const jobData = { ...req.body };
  if (req.admin) jobData.createdBy = req.admin.id;

  const job = await Job.create(jobData);

  return res.status(201).json({
    success: true,
    message: 'Job created successfully',
    data: job,
  });
};

/**
 * PATCH /api/jobs/:id
 * Partially update a job posting.
 * If title changes, a new slug is generated (unless slug is explicitly provided).
 * Only accessible to authenticated admins.
 */
exports.updateJob = async (req, res) => {
  const { id } = req.params;

  const updateData = { ...req.body };
  if (req.admin) updateData.lastEditedBy = req.admin.id;

  // If title changes and no explicit slug provided, regenerate slug
  if (updateData.title && !updateData.slug) {
    const baseSlug = slugify(updateData.title, { lower: true, strict: true });
    // Resolve potential collision
    let slug = baseSlug;
    let counter = 1;
    while (true) {
      const existing = await Job.findOne({ slug, _id: { $ne: id } });
      if (!existing) break;
      slug = `${baseSlug}-${counter}`;
      counter++;
    }
    updateData.slug = slug;
  }

  // Auto-update SEO meta if title changed
  if (updateData.title && updateData.seo === undefined) {
    updateData['seo.metaTitle'] = `${updateData.title} ${new Date().getFullYear()} | SarkariSetu`;
  }

  const job = await Job.findByIdAndUpdate(
    id,
    { $set: updateData },
    {
      new: true,          // return updated document
      runValidators: true, // run schema validators on update
    }
  );

  if (!job) {
    return res.status(404).json({ success: false, message: 'Job not found' });
  }

  return res.json({ success: true, message: 'Job updated successfully', data: job });
};

/**
 * DELETE /api/jobs/:id
 * Permanently delete a job posting.
 * Only accessible to super_admin.
 */
exports.deleteJob = async (req, res) => {
  const { id } = req.params;

  const job = await Job.findByIdAndDelete(id);

  if (!job) {
    return res.status(404).json({ success: false, message: 'Job not found' });
  }

  return res.json({ success: true, message: 'Job deleted successfully' });
};

/**
 * PATCH /api/jobs/:id/publish
 * Toggle a job's status between 'published' and 'draft'.
 */
exports.togglePublish = async (req, res) => {
  const { id } = req.params;

  const job = await Job.findById(id);
  if (!job) return res.status(404).json({ success: false, message: 'Job not found' });

  job.status = job.status === 'published' ? 'draft' : 'published';
  if (job.status === 'published' && !job.publishedAt) {
    job.publishedAt = new Date();
  }

  await job.save();

  return res.json({
    success: true,
    message: `Job is now ${job.status}`,
    data: { id: job._id, slug: job.slug, status: job.status },
  });
};

/**
 * GET /api/jobs/trending
 * Returns trending jobs (by view count + flag), useful for homepage.
 */
exports.getTrending = async (req, res) => {
  const limit = parseInt(req.query.limit, 10) || 10;
  const days  = parseInt(req.query.days, 10)  || 7;

  const jobs = await Job.findTrending(limit, days);

  return res.json({ success: true, data: jobs });
};

/**
 * GET /api/jobs/:id/related
 * Returns related jobs for a given job.
 * Strategy: same jobType + state, excluding current job.
 */
exports.getRelatedJobs = async (req, res) => {
  const { id } = req.params;
  const limit = parseInt(req.query.limit, 10) || 5;

  const sourceJob = await Job.findById(id).select('jobType state qualification category').lean();
  if (!sourceJob) return res.status(404).json({ success: false, message: 'Job not found' });

  const related = await Job.find({
    _id: { $ne: id },
    status: 'published',
    $or: [
      { jobType: sourceJob.jobType, state: sourceJob.state },
      { category: sourceJob.category },
      { qualification: sourceJob.qualification },
    ],
  })
    .sort({ viewCount: -1, createdAt: -1 })
    .limit(limit)
    .select('title slug organization state jobType featuredImage shortDescription')
    .lean();

  return res.json({ success: true, data: related });
};

/**
 * GET /api/jobs/slugs
 * Returns all published slugs (for Next.js generateStaticParams / sitemap).
 */
exports.getAllSlugs = async (req, res) => {
  const jobs = await Job.find({ status: 'published' })
    .select('slug updatedAt')
    .lean();

  return res.json({ success: true, data: jobs });
};

/**
 * PATCH /api/jobs/:id/download
 * Increment download counts for admit card or result.
 */
exports.incrementDownload = async (req, res) => {
  const { id } = req.params;
  const { type } = req.query; // 'admitCard' or 'result'

  if (!['admitCard', 'result'].includes(type)) {
    return res.status(400).json({ success: false, message: 'Invalid download type' });
  }

  const updateField = type === 'admitCard' ? 'admitCardDownloadCount' : 'resultDownloadCount';
  
  const job = await Job.findByIdAndUpdate(id, { $inc: { [updateField]: 1 } }, { new: true });

  if (!job) {
    return res.status(404).json({ success: false, message: 'Job not found' });
  }

  return res.json({ success: true, data: { [updateField]: job[updateField] } });
};

module.exports = exports;
